### ISSUE TITLE
pod 安装出现错误

### ISSUE THREAD

**Issue by chenfengfeng** [AsTryE/PrettyRuler#1]
[!] /usr/bin/git clone https://github.com/804145113/PrettyRuler.git /var/folders/f6/5b3psg054y36qfbj4wp8njqr0000gn/T/d20161031-5895-volsoy --template= --single-branch --depth 1 --branch 2.1.0

Cloning into '/var/folders/f6/5b3psg054y36qfbj4wp8njqr0000gn/T/d20161031-5895-volsoy'...
warning: Could not find remote branch 2.1.0 to clone.
fatal: Remote branch 2.1.0 not found in upstream origin

**Comment by AsTryE** [comment]
pod文件怎么写的

**Comment by AsTryE** [comment]
你好，刚试了下，我这面是正常的。pod文件里面写： pod 'PrettyRuler','~> 2.1.1'，所以你那里可能是网络问题所导致。同样，最近我更新其他的第三方库的时候也遇到过这种问题，但再一次执行pod install就可以成功安装了。从你错误信息看来，branch 2.1.0，最新应该是2.1.1，可以执行pod search PrettyRuler查看库的版本。

**Comment by chenfengfeng** [comment]
我 search 了下显示2.1.1版本,我更新下本地库再试试😬

**Comment by chenfengfeng** [comment]
appledeMacBook-Pro:onlys-ios Apple$ pod repo update
Updating spec repo `master`
  $ /usr/bin/git -C /Users/apple/.cocoapods/repos/master pull --ff-only
  From https://github.com/CocoaPods/Specs
     4df8535..5037da9  master     -> origin/master
  Updating 4df8535..5037da9
  Fast-forward
   .../0.0.21/JYObjectModule.podspec.json             | 45 ++++++++++++++++++++++
   1 file changed, 45 insertions(+)
   create mode 100644 Specs/JYObjectModule/0.0.21/JYObjectModule.podspec.json

CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

appledeMacBook-Pro:onlys-ios Apple$ pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `PrettyRuler (~> 2.1.1)` required by `Podfile`

Specs satisfying the `PrettyRuler (~> 2.1.1)` dependency were found, but they required a higher minimum deployment target.

Podfile文件:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'onlys' do

pod 'PrettyRuler', '~> 2.1.1'

**Comment by chenfengfeng** [comment]
会不会是你文件地址写的有问题,我查了下你的文件地址是写
'Source:   https://github.com/804145113/PrettyRuler.git'
但是你git 的地址是:'https://github.com/AsTryE/PrettyRuler'

**Comment by AsTryE** [comment]
之前没注意target设置的iOS9，现在改成iOS7了，你看 Specs satisfying the PrettyRuler (~> 2.1.1) dependency were found, but they required a higher minimum deployment target. 这段错误，就知道问题了。至于你说的地址，我也更正了，不过地址应该没什么问题。因为以前的名字804145113，后面改昵称AsTryE导致显示不同，但发现两个地址都能访问，所以github服务器上面应该映射了路径的。

**Comment by chenfengfeng** [comment]
嗯嗯,这样应该好了,我还没试,明天去测试下~
